### ISSUE TITLE
Inbuilt reflectivity calculator produces incorrect output in a corner case

### ISSUE THREAD

**Issue by andyfaff** [algreco/mlreflect#1]
I've been adding mlreflect to the ORSO validation suite, https://github.com/reflectivity/analysis/pull/65. There is a corner case that the inbuilt reflectivity calculator in `mlreflect` is not handling correctly. This case involves a dip before the critical edge when there is absorption in one of the layers.

The MWE for reproducing this issue is below:

```
import numpy as np
import matplotlib.pyplot as plt
q = np.linspace(0.01, 0.05, 1001)
w = np.array([[0.00e+00, 0e+00, 0.00e+00, 0], 
              [1.20e+03, 4.66e+00, 1.60e-02, 1.00e+01],
              [0.00e+00, 6.36e+00, 0.00e+00, 3.00e+00]])

from refnx.reflect.reflect_model import abeles
from mlreflect.data_generation.reflectivity import multilayer_reflectivity

thickness = w[-2:0:-1, 0]
sld = w[:0:-1, 1] + 1J * w[:0:-1, 2]
roughness = w[:0:-1, 3]

ml = multilayer_reflectivity(q* 1e10, thickness*1e-10, roughness*1e-10, sld* 1e14, ambient_sld=w[0, 1]* 1e14)
ab = abeles(q, w)

plt.plot(q, ml)
plt.plot(q, ab)
plt.yscale('log')
np.testing.assert_allclose(ml, ab, rtol=8e-5)
```

If you have any comments for how mlreflect can be included in that validation suite in a better fashion please let me know.

**Comment by algreco** [comment]
Hi Andrew!
Thank you for putting in the work of testing our simulation code with the ORSO suite! I'm looking into the issue right now. I presume it's related to how complex numbers are handled.

**Comment by andyfaff** [comment]
If it's what I think it is, then it's bitten most of us at one point or another. I think it's due to the wrong branch cut being selected on a complex sqrt, https://github.com/refnx/refnx/blob/master/refnx/reflect/_reflect.py#L212

(see also https://gist.github.com/andyfaff/6f4c8a17fb8f9af804f395b932e6cac0 for speed comparison between different calculation kernels)

**Comment by algreco** [comment]
Wow, thanks! This really seems to have been the problem. I will implement a similar solution to what you have suggested asap. Although in general I would recommend installing also Refl1D to do the simulations, since it is much faster and also has been validated by the ORSO suite. We might also implement other kernels in the future.

**Comment by algreco** [comment]
I now implemented a similar solution to select the correct branch cut and added a small test. However, we recommend using the Refl1D kernel instead of the built-in one as we're considering moving fully to kernels from established packages for reflectivity simulation.
