### ISSUE TITLE
Improve documentation on `mlreflect.data_generation.reflectivity.multilayer_reflectivity`

### ISSUE THREAD

**Issue by andyfaff** [algreco/mlreflect#2]
I have had a hard time trying to use the [`mlreflect.data_generation.reflectivity.multilayer_reflectivity`](mlreflect.data_generation.reflectivity.multilayer_reflectivity) function.

The documentation states that the thickness, roughness and scattering_length_density need to be in SI units. Unfortunately I was trying to use nm. Could you make it clear that they should be in SI *base* units, and mention the actual unit. i.e.
thickness: m
SLD: m**-2
roughness: m

Moreover, the docstring for q doesn't mention any units. It actually accepts reciprocal Angstrom, not reciprocal metres. Could you add units for q?

**Comment by andyfaff** [comment]
Could you also add an example in that docstring for how to use the function to calculate a reflectivity curve?

**Comment by algreco** [comment]
Thank you for pointing this out! I updated the units and added an example to the docstrings. Please don't hesitate to open another Issue if necessary.
