### ISSUE TITLE
No tests for examining the output of `mlreflect.data_generation.reflectivity.multilayer_reflectivity`

### ISSUE THREAD

**Issue by andyfaff** [algreco/mlreflect#3]
As one of the key components of the mlreflect package I would expect to have various tests examining the output of `mlreflect.data_generation.reflectivity.multilayer_reflectivity` for correctness, I can't find any in the test suite.

Is there a plan to use continuous integration (e.g. github actions) for running the test suite automatically when you make changes to the package?

**Comment by algreco** [comment]
Thank you for your comment!

We're considering including CI for the GitHub repository in the future. However, since some of the machine learning-related tests are a bit resource intensive, we're only using the CI workflow on our internal repository so far (run on private university servers).

**Comment by algreco** [comment]
I'm closing this Issue since we're presently looking into moving away from the built-in kernel (see #1) and thus are not planning to write extensive tests for it.
I case we decide to stick with the built-in kernel, we will make sure to test it properly.
